[supervisord]
nodaemon=true
user=root

[program:xvfb]
command=Xvfb :1 -screen 0 1024x768x24
autorestart=true
priority=10

[program:vnc]
command=tigervncserver :1 -geometry 1024x768 -depth 24 -localhost no -SecurityTypes None
autorestart=true
priority=20

[program:xfce4]
command=startxfce4
environment=DISPLAY=":1"
autorestart=true
priority=30

[program:novnc]
command=/usr/share/novnc/utils/novnc_proxy --vnc localhost:5901 --listen 8080
autorestart=true
priority=40

[program:ksatria_game]
command=java -jar /app/res.jar
environment=DISPLAY=":1"
directory=/app
autorestart=true
priority=50
